# Generated by Django 5.2.4 on 2025-08-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_inquiry'),
    ]

    operations = [
    ]
