# Generated by Django 5.2.4 on 2025-08-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20250821_1725'),
    ]

    operations = [
    ]
